# Utiliser l'image tiangolo/uvicorn-gunicorn-fastapi optimisée pour FastAPI
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

# Définir le répertoire de travail à /app
WORKDIR /app

# Copier tous les fichiers du répertoire courant dans /app
COPY . /app

# Exposer le port 80
EXPOSE 80

# Démarrer Uvicorn avec le fichier main.py et l'application FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]

