name: Deploy to Production

on:
  push:
    branches:
      - main  # Le déploiement est déclenché par un push dans la branche principale.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /path/to/your/app  # Chemin vers votre application sur le serveur.
          git pull origin main   # Mettre à jour le dépôt sur le serveur.
          docker-compose down    # (Optionnel) Arrêter les anciens conteneurs Docker.
          docker-compose up --build -d  # Redémarrer l'application avec Docker Compose.
        EOF
